spring:
  datasource:
    url: jdbc:postgresql://crewcash-postgres/crewcashdb_sharing
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://crewcash-keycloak/realms/CrewCash
