apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: sharing-config
    files:
      - application.yml
    options:
      labels:
        app: sharing-service
